### PR TITLE
Fix Metabiome's modules

### PR DESCRIPTION
**Pull request by biocdgv**
- Set metabiome-maxbin2, metabiome-concoct and metabiome-maxbin2
as separated modules. 
- Merge metabiome-humman2 module into metabiome-taxonomic-profiling

Please check it out through the branch `metabiome-envs-docs`!!

:paintbrush: :paintbrush: :paintbrush: :paintbrush: :paintbrush: :paintbrush:

### CODE REVIEW

**Review by Nesper94 — COMMENTED** [review]
Hi Cristian! Looks good to me. Maybe we should make the changes associated with these environments too (e. g. add the modules to `install.sh` and `uninstall.sh`, add the `.yml` files, etc.) in another branch derived from `dev`, what do you think?

**Review by Estefany-Lorenzana — APPROVED** [review]
I see everything okay!

**Comment by biocdgv** [comment]
Hello Juan! Thanks for reviewing! I agree with you  

> Maybe we should make the changes associated with these environments too (e. g. add the modules to install.sh and uninstall.sh, add the .yml files, etc.) in another branch derived from dev, what do you think?

Do you mean in the create_envs function?  Like changing 
```
echo "Creating preprocessing environment..."
 conda env create --file "$METABIOME_DIR"/conda-envs/preprocessing.yml
```
for 
```
echo "Creating Metabiome preprocessing module"
 conda env create --file "$METABIOME_DIR"/conda-envs/preprocessing.yml
```
Or what do you mean? :crying_cat_face:

**Review by Nesper94 — APPROVED** [review]
No, sorry, the changes I was talking about were already implemented. I think we can do the merge now.

**Pull request merged**
